### ISSUE TITLE
[Feature] Start des esb0 trotz nicht validierter Artefakte

### ISSUE THREAD

**Issue by h9h** [karalus/esb0#5]
Wir haben die Situation, dass wir manchmal den ESB0 nicht starten können, weil ein Service eine Exception wirft "Could not validate artifact".
Wir hätten den Wunsch, dass man konfigurieren kann, ob des Start dann abbricht oder dieser Service nur mit einer entsprechenden Fehlermeldung geloggt wird und der ESB0 trotzdem startet.

Hier ein Beispiel der Fehlermeldung, wenn der ESB0 nicht startet:

`[com.artofarc.esb.servlet.ESBServletContextListener]

                java.lang.RuntimeException: Could not initialize services
                               at com.artofarc.esb.servlet.ESBServletContextListener.createContext(ESBServletContextListener.java:62)
                               at com.artofarc.esb.servlet.ESBServletContextListener.contextInitialized(ESBServletContextListener.java:80)
                               at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
                               at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
                               at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                               at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
                               at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
                               at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                               at java.lang.Thread.run(Thread.java:748)

                Caused by: Could not validate artifact /consumer/Papyrus.user.DokumentVerteilungPort1.xservice@155
                               at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                               at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                               at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                               at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                               at com.artofarc.util.ReflectionUtils.convert(ReflectionUtils.java:260)
                               at com.artofarc.esb.artifact.ServiceArtifact.transform(ServiceArtifact.java:170)
                               at com.artofarc.esb.artifact.ServiceArtifact.transform(ServiceArtifact.java:483)
                               at com.artofarc.esb.artifact.ServiceArtifact.transform(ServiceArtifact.java:167)
                               at com.artofarc.esb.artifact.ServiceArtifact.validateInternal(ServiceArtifact.java:108)
                               at com.artofarc.esb.artifact.Artifact.validate(Artifact.java:217)
                               at com.artofarc.esb.artifact.FileSystem$1.call(FileSystem.java:163)
                               at com.artofarc.esb.artifact.FileSystem$1.call(FileSystem.java:1)
                               ... 4 more`

**Comment by karalus** [comment]
Done with https://github.com/karalus/esb0/commit/6575bff32fa7d6ef84a9f71911d0638f0f8b4627
